### ISSUE TITLE
Baseline option

### ISSUE THREAD

**Issue by mdq-rab2b** [LambdaTest/smartui-cli#57]
I know it's a pretty "basic" implementation, as it has very few configuration options, however, it works super well.
Is there any way to add the option to set the baseline?

Thanks

[docs](https://www.lambdatest.com/support/docs/smartui-cli/#smartui-cli-config-options)

FILE: `smartui-web.json`

```
{
  "web": {
    "browsers": [ "chrome" ],
    "viewports": [ [ 1920 ] ],
    "waitForTimeout": 1000,
    "enableJavaScript": false
  }
}
```

**Comment by JeeveshJ7** [comment]
Hi @mdq-rab2b 
We are currently following a Git based baseline strategy for SmartUI SDK. You can read more about the know-hows of baseline changes here - (https://www.lambdatest.com/support/docs/smartui-git-branching-strategy/#git-branching-workflows-and-strategies)

More about SmartUI SDK - https://www.lambdatest.com/support/docs/smartui-selenium-js-sdk/

Having said that, in future releases there will be an option to set the baseline in config itself, as well!

Glad you are liking the SmartUI SDK!

Feel free to reach out to support@lambdatest.com in case you face any issues.

Best
SmartUI Team
